import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import Link from "next/link"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-hidden antialiased`}
      >
        <div className=" text-white w-full  glow-text   p-4 bg-gradient-to-r from-gray-900 to-black  grid grid-cols-4   ">
          <div className="   ">
            <Link href={"/landing"}>
              <h1 className="cursor-pointer w-max  hover:scale-y-150  font-bold text-lg">
                intro
              </h1>
            </Link>
          </div>
          <div>
            <Link href={"/"}>
              <h1 className="cursor-pointer w-max  hover:scale-y-150  font-bold text-lg">
                solar
              </h1>
            </Link>
          </div>
          <div>
            <Link href={"/projects"}>
              <h1 className="cursor-pointer w-max hover:scale-y-150  font-bold text-lg">
                projects
              </h1>
            </Link>
          </div>
          <div>
            <Link href={"/resume"}>
              <h1 className="cursor-pointer w-max hover:scale-y-150   font-bold text-lg">
                resume
              </h1>
            </Link>
          </div>
        </div>
        <div>{children}</div>
      </body>
    </html>
  )
}
